[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.test]
toolchain = "nightly"
command = "cargo"
args = ["test", "--release", "--target", "aarch64-apple-darwin", "--", "--nocapture"]

[tasks.build]
toolchain = "nightly"
command = "cargo"
args = ["build"]

[tasks.fmt]
toolchain = "nightly"
command = "cargo"
args = ["fmt"]

[tasks.dev-test-flow]
dependencies = [
    "fmt",
    "build",
    "test",
]